### ISSUE TITLE
Create dedicated orders view for client

### ISSUE THREAD

**Issue by lukaszreszke** [RailsEventStore/ecommerce#104]
Currently, when a user logs in as a specific client `/client` they see a list of submitted orders.  Paid, Expired and Cancelled orders are also visible. The user has the possibility to navigate to a specific order and see its details by clicking the order's number.

Then they're redirected to that order at `/orders/id` URL. The `/orders` URL is dedicated to being used by the shops' staff, not the client itself.
 
Therefore new view should be created for the client to see its orders. The view should contain ordered items and their final price.

**Comment by krzykamil** [comment]
https://github.com/RailsEventStore/ecommerce/pull/124
