### ISSUE TITLE
Pass cqrs object everywhere consistently

### ISSUE THREAD

**Issue by andrzejkrzywda** [RailsEventStore/ecommerce#106]
Now in some places it's event store.
(another debate how to rename this object)

**Comment by pawelpacana** [comment]
[RBS](https://github.com/ruby/rbs) helps tracking down such unintented usage.

In RES we've used it to ensure common interface for repositories. We had a [signature file](https://github.com/RailsEventStore/rails_event_store/blob/92d8c763f89fba0bf9c5f16586d4b314a98fb097/ruby_event_store/sig/res.rbs) describing accepted types and there was a verification step when running units:
```
env RBS_TEST_LOGLEVEL=error rbs test RBS_TEST_RAISE=true --target RubyEventStore::InMemoryRepository rspec
```

**Comment by andrzejkrzywda** [comment]
as for the "renaming" debate - new candidates: `Bus` or `MessageBus`

**Comment by andrzejkrzywda** [comment]
I think I'm ready to remove this whole cqrs/bus object at all, back where it was and pass both event_store and command_bus where needed. The `process` methods and other DSL could be then extracted to classes like `Infra::Process.new(event_store, command_bus`.

**Comment by andrzejkrzywda** [comment]
The feature was removed.
