### ISSUE TITLE
Display Shipments

### ISSUE THREAD

**Issue by andrzejkrzywda** [RailsEventStore/ecommerce#149]
Let's create a new menu item called "Shipments".

A list of those orders which have Shipment assigned will appear.

Probably we only need to react to "Shipment*" events.
The output would be an ActiveRecord model ShipmentsList::Shipment with shipment_id/order_id, address, status.

**Comment by saksham-jain** [comment]
hey @andrzejkrzywda can I take this issue?
Also if there are any other details kindly share.

**Comment by andrzejkrzywda** [comment]
Go for it.

I'd recommend looking at other read models and follow the conventions.

**Comment by saksham-jain** [comment]
@andrzejkrzywda having some questions. 
- Address would be a combination of all 4 lines?
- In the first column do we need to show the order name or order uid?
- How to get the status of the shipment?

**Comment by andrzejkrzywda** [comment]
- yes
- name sounds better, how do you think?
- we now have only 2 states, Shipped or not Shipped (from the user perspective), I think `ShipmentSubmitted` is the fact which changes the state

**Comment by saksham-jain** [comment]
Okay, I still cannot figure out how to get shipment state. I will raise a PR having a shipment page without the state. Please guide me through how I can get state.

This is how shipment page would look like
<img width="1173" alt="Screenshot 2022-08-20 at 3 35 56 PM" src="https://user-images.githubusercontent.com/27828987/185740801-09343465-9322-4a76-b69e-a971399b8d6d.png">

**Comment by andrzejkrzywda** [comment]
Thanks for the screenshot!

I understand the issue with displaying the state - let's remove it for now.

As for the link to order - we can extract it to another issue - I understand it's a bit more tricky.

**Comment by saksham-jain** [comment]
okay @andrzejkrzywda removed state column.
