### ISSUE TITLE
Remove the cqrs object, replace with explicit event_store and command_bus

### ISSUE THREAD

**Issue by andrzejkrzywda** [RailsEventStore/ecommerce#189]

**Comment by jandudulski** [comment]
What do you mean?

**Comment by andrzejkrzywda** [comment]
Right now, cqrs is a facade over both event_store and command_bus. By grouping them it allowed for building/tracking some relations between events and commands. However, this concept was confusing to many new people and as such it brings more problems than benefits.

The whole idea of tracking events/commands dependency is still valid and needed. We just need to find other ways to do it.

Removing the cqrs object is already in progress. We replace the cqrs with both event_store and command_bus, explicitly being passed where needed.

A bit cumbersome refactoring, but thanks to good tests it's going well.

**Comment by andrzejkrzywda** [comment]
I see that the issue title could be confusing, I changed the name. Thanks!

**Comment by lukaszreszke** [comment]
The CQRS facade is now gone (▀̿Ĺ̯▀̿ ̿)
