### ISSUE TITLE
Change synchronous event handlers to asynchronous

### ISSUE THREAD

**Issue by lukaszreszke** [RailsEventStore/ecommerce#206]

**Comment by andrzejkrzywda** [comment]
Is this ticket still in progress @lukaszreszke ? Maybe we can extract smaller tickets here for others to take?

**Comment by lukaszreszke** [comment]
I'll extract smaller ones.
When it comes to read models, there are two read models that need to be reworked. One in readmodels/products and the other one in readmodels/public_offer

**Comment by lukaszreszke** [comment]
Extracted _leftovers_ to #255 and #256
