### ISSUE TITLE
db:seeds silently not working properly when sidekiq doesn't run

### ISSUE THREAD

**Issue by andrzejkrzywda** [RailsEventStore/ecommerce#222]
Just documenting one debugging session with @panSarin - maybe the problem can be solved in many ways.

Or maybe it's not a problem at all.

The issue was, that seeds where run. But, sidekiq wasn't running. Which means that commands were executed, events were published. Here all was good. But because the read models are now async, we didn't see any error easily that workers are not running. In the end, the application was in a not consistent state.

It would be solved if `bin/dev` was run as stated in the README.

Sidenote: `bin/dev` requires foreman - we may want to make a decision if we want to suggest foreman locally or make it part of Makefile.

Another sidenote: maybe we should have the top-level Makefile to contain a task `make run` or something, which would cover all the details below.

**Comment by lukaszreszke** [comment]
* [Added dev command to make file that runs all the components](https://github.com/RailsEventStore/ecommerce/commit/34359d7924b8e8f72804609444cf647edd2e9a57)
* [Removed the procfile.dev so bin/dev is not possible anymore](https://github.com/RailsEventStore/ecommerce/commit/2c2be4019543b0243a445089a04793ac9f81239f)
* [Updated README.md](https://github.com/RailsEventStore/ecommerce/commit/3461a6c6369efd97a9fc34a9b3f94185f88e39a1)

It should be okay for newcomers.
