### ISSUE TITLE
Give ability to show the lowest price in the last 30 days

### ISSUE THREAD

**Issue by bglowacki** [RailsEventStore/ecommerce#223]
There is a new UE Directive in UE that obliges shops to show the lowest price in last 30 days.

[Omnibus Directive](https://ecommerce-europe.eu/news-item/omnibus-directive-enters-into-application-at-national-level/)

It would be helpful to add it to the ecommerce

**Comment by bryszard** [comment]
I'm interested and I will try to approach this in the following weekend most probably. Of course, feel free to reject the idea or take your own stance on it, don't feel blocked by me :).
