### ISSUE TITLE
Move Omnibus directive related stuff from ClientOrders to PublicOffer read model

### ISSUE THREAD

**Issue by pjurewicz** [RailsEventStore/ecommerce#268]
Related to #224.
The goal is to move Omnibus price info from the ClientOrders to the PublicOffer read model.

**Comment by bryszard** [comment]
The thing is - we are supposed to show it to clients in the moment they are making an order too, right? They might not even look at the `Products` page and go straight to making an order. And we're using there the `ClientOrders::Product`, not `PublicOffer::Product`.

Unless - we're not really going to inform about promotions when client is making an order. The directive requires to show this information when informing consumers about the promotion / special offer. So if we only show promotions on `PublicOffer` part, then we should be fine with keeping it there.

**Comment by pjurewicz** [comment]
Yes, PublicOffer is a view for showing promotions.
Thanks, I'm closing this.
