### ISSUE TITLE
Coupons

### ISSUE THREAD

**Issue by andrzejkrzywda** [RailsEventStore/ecommerce#35]

**Comment by andrzejkrzywda** [comment]
@panSarin maybe you would like to challenge yourself with this feature? 😎

**Comment by andrzejkrzywda** [comment]
we want to mimic this

https://support.getdpd.com/hc/en-us/articles/201282573-Creating-Coupons-in-DPD

as the first story, only create and percentage discount is fine

**Comment by krzykamil** [comment]
:thinking: Is this still a thing? I saw a lot of code connected to discounts, isin't that the same thing?

**Comment by andrzejkrzywda** [comment]
what we have right now is discounts directly assigned by sales people (at the moment only they can create orders).

what we need in this ticket is to have "codes" which enable discounts. it's still a bit artificial as they would be entered by sales people but later it can be used by clients directly (when we finish the ticket where clients can create their orders).

we need a way of creating a coupon where "arkency20" would enable a discount of some value, probably 20%.

so a form with discount name, value and percentage - in UI terms

**Comment by krzykamil** [comment]
Alright, I'd like to take this issue then

**Comment by krzykamil** [comment]
I prepared something: https://github.com/RailsEventStore/ecommerce/pull/127 would appreciate any feedback

**Comment by bryszard** [comment]
Shall this be closed?

**Comment by krzykamil** [comment]
Yea, the basic functionality requested is done, I'll add PR that fixes the issues from comments from that PR this week

**Comment by andrzejkrzywda** [comment]
I'm reopening this issue.

Currently we can create coupons, but it seems they can't be used in any way.
As such this feature is not bringing any business value.

We should extend the ordering process with the possibility of providing the coupon. As a result the order will have the associated discount.

**Comment by andrzejkrzywda** [comment]
Now that a cart is ready on the client side, we can add buttons to use the coupon from the client perspective

**Comment by andrzejkrzywda** [comment]
Assumptions:

* using such coupon makes sense from the client perspective
* It makes less sense from the admin/sales perspective to have this in their UI (they already have the option to set discount)
* we can rely on the existing logic for setting discount on orders (ensuring there is only discount at a time is handled there)

1. Introduce a new command `UseCoupon`, with `order_id` and `coupon_id`
2. Introduce a new event `CouponUsed` with the same attributes
3. React to `CouponUsed` in the `ClientOrders` read model and display on the view
4. React to `CouponUsed` in the `Orders` read model and display on the view
5. Create a simple process, when `CouponUsed` happens - trigger the `SetPercentageDiscount` command
6. Extend `orders/edit` view (or a new view) to display a field for entering coupon code
