### ISSUE TITLE
Invoice generation

### ISSUE THREAD

**Issue by andrzejkrzywda** [RailsEventStore/ecommerce#37]

**Comment by andrzejkrzywda** [comment]
This is done, right @pjurewicz ?

**Comment by bryszard** [comment]
I don't see it deployed to ecommerce.arkademy.dev, but I can certainly see it on localhost:

<img width="1164" alt="image" src="https://user-images.githubusercontent.com/12682792/169909915-22e46e32-a2ab-4a87-b984-b00e8a4b2658.png">

**Comment by krzykamil** [comment]
It is done, including heroku app I went through the whole process on heroku 
https://ecommerce.arkademy.dev/invoices/0743f6d6-6c74-4380-90e9-03396ff89a95
https://ecommerce.arkademy.dev/re
![2022-05-25-173717_1277x323_scrot](https://user-images.githubusercontent.com/25006471/170302325-7cf5a3a4-b57a-49bc-aaf4-efca7035d853.png)
![2022-05-25-173726_1266x761_scrot](https://user-images.githubusercontent.com/25006471/170302335-8e5023db-22d4-4350-9fa1-3403297564ab.png)
s
