### ISSUE TITLE
Removing order discounts

### ISSUE THREAD

**Issue by andrzejkrzywda** [RailsEventStore/ecommerce#55]
Currently we allow setting orders discount via the UI. It would be nice to be able to remove them

**Comment by jandudulski** [comment]
@andrzejkrzywda do you mean something like this:

![image](https://user-images.githubusercontent.com/153103/142475771-0b893ae4-92a0-4fa1-921b-6935f4565bd2.png)

?

**Comment by andrzejkrzywda** [comment]
Yes, should be fine.
