### ISSUE TITLE
Archiving old orders

### ISSUE THREAD

**Issue by andrzejkrzywda** [RailsEventStore/ecommerce#57]
The orders screen becomes messy after some time. 

Let's allow to archive specific orders - they would then disappear from the main screen.

**Comment by lukaszreszke** [comment]
Hey Andrzej. Quick question regarding archiving the order itself.

Is it possible to archive order at every step?

**Comment by andrzejkrzywda** [comment]
The more I think of it - the less I like this feature 

We probably don't need it and we can address the problem somewhat differently.
