### ISSUE TITLE
Heroku deployment does not run migrations

### ISSUE THREAD

**Issue by pawelpacana** [RailsEventStore/ecommerce#78]

**Comment by israelb** [comment]
@pawelpacana  Do you use something like a custom **Buildpack** to deploy it to Heroku? Or what is the way to deploy correctly this kind of structure? I did not find anything in the docs about this topic, only that one workflow `rails_application.yml` is deploying directly to the _rails_application_ directory

**Comment by pawelpacana** [comment]
It's a custom buildpack: https://github.com/arkency/heroku-buildpack-ruby-monorepo

**Comment by pawelpacana** [comment]
```
remote: -----> Launching...
remote:  !     Release command declared: this new release will not be available until the command succeeds.
remote:        Released v343
remote:        https://res-ecommerce-rails.herokuapp.com/ deployed to Heroku
remote:
```

Done via https://github.com/RailsEventStore/ecommerce/commit/b7be0a9f03fde5b92f62f3e263f5f5627c75b285
